import Head from "next/head";
import { Inter } from "next/font/google";
import { Header } from "@/src/components/Header/Header";
import dynamic from "next/dynamic";
import styles from "@/styles/Index.module.css";
import AddressTextField from "@/src/components/TextField/Address";
import { AppStateProvider } from "@/src/hooks/AppStateContext";
import Details from "@/src/components/Section/Details";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const GoogleMaps = dynamic(() => import("../src/components/Map/GoogleMaps"), {
    ssr: false,
  });
  return (
    <>
      <Head>
        <title>SAC - UFO DO RIO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppStateProvider>
          <div>
            <Header />
            <div className={styles.container}>
              <AddressTextField />
            </div>
            <div className={styles.container}>
              <GoogleMaps />
            </div>
            <div>
              <Details />
            </div>
          </div>
        </AppStateProvider>
      </main>
    </>
  );
}
